image: jekyll/builder

stages:
  - deploy

before_script:
  - gem install pygments.rb

# cache:
#   paths:
#     - node_modules/
#     - bower_components/
#   key: "$CI_BUILD_REPO"

sample_deploy:
  stage: deploy
  only:
    - master
    - development
  script:
    - bundle install
    - jekyll build
  artifacts:
    paths:
      - _site/
