image: "registry.gitlab.com/rpadovani/rpadovani.com:latest"
stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: eu-central-1

cache:
  paths:
    - vendor

buildJekyll:
  stage: build
  script:
    - bundle install --path=vendor/
    - bundle exec jekyll build --future # The server is in another timezone..
  artifacts:
    paths:
      - _site/
  except:
    - master

deploy_site:
  stage: deploy
  only:
    - master
  script:
    - bundle install --path=vendor/
    - bundle exec jekyll build --future # The server is in another timezone..
  artifacts:
    paths:
      - _site/

deploys3:
  image: "python:latest"
  stage: deploy
  dependencies:
    - buildJekyll
  before_script:
    - pip install awscli
  script:
    - aws s3 cp _site s3://gitlabrunner-s3-static/${CI_COMMIT_REF_SLUG} --recursive
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: http://gitlabrunner-s3-static.s3-website.eu-central-1.amazonaws.com/${CI_COMMIT_REF_SLUG}
    on_stop: clean_s3
  except:
    - master

clean_s3:
  image: "python:latest"
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 rm s3://gitlabrunner-s3-static/${CI_COMMIT_REF_SLUG} --recursive
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    action: stop
  when: manual
  except:
    - master
