image: jekyll/builder

stages:
  - deploy

# cache:
#   paths:
#     - node_modules/
#     - bower_components/
#   key: "$CI_BUILD_REPO"

sample_deploy:
  stage: deploy
  only:
    - master
    - development
  script:
    - bundle install
    - bundle exec jekyll build
    - bundle exec htmlproofer ./_site --disable-external
  artifacts:
    paths:
      - _site/
