image: jekyll/builder:builder

stages:
  - deploy

# cache:
#   paths:
#     - node_modules/
#     - bower_components/
#   key: "$CI_BUILD_REPO"

sample_deploy:
  stage: deploy
  only:
    - master
  script:
    - bundle install
    - bundle clean --force
    - bundle exec jekyll build --destination /tmp/build
    - htmlproof /tmp/build --empty-alt-ignore
  artifacts:
    paths:
      - /tmp/build
