image: ruby:2.3
stages:
  - deploy

cache:
  paths:
    - vendor
    - .bundle
  key: "$CI_BUILD_REPO"

before_script:
  - gem install bundler

sample_deploy:
  stage: deploy
  only:
    - master
  script:
    - bundle install
    - bundle exec jekyll build --destination /tmp/build
    - bundle htmlproof /tmp/build --empty-alt-ignore
  artifacts:
    paths:
      - /tmp/build
