# Base URL
baseurl: #baseurl

# Site live URL
url: http://localhost:4000

# Extension for generated URLs. Used by Gitlab Pages since it requires the file extension
extension: #.html

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Riccardo Padovani
  description: I mainly throw fairy dust to clouds, blog boring stuff, and enjoy life.
  meta_description: > #
    I enjoy new challenges and learning new things. I'm an incurable optimist who loves implementing tools to enable people working on their goals, and finding solutions to hard problems. 
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Riccardo Padovani
    email: riccardo@rpadovani.com
    url: https://www.rpadovani.com


# Conversion / Build settings
markdown:    kramdown

# Permalinks
permalink:        pretty

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - vendor

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
